/**
 * Interface for Wikipedia search results
 */
export interface WikipediaSearchResult {
  title: string;
  description: string;
  url: string;
}

/**
 * Interface for Wikipedia API response structure
 */
export interface WikipediaApiResponse {
  query?: {
    search?: Array<{
      title: string;
      snippet: string;
      pageid: number;
    }>;
  };
}

/**
 * Interface for search state management
 */
export interface SearchState {
  isLoading: boolean;
  results: WikipediaSearchResult[];
  error: string | null;
  hasSearched: boolean;
}

// code generated by AI
