import { Component, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormControl, ReactiveFormsModule } from '@angular/forms';
import { WikiService, WikiArticleSummary } from '../services/wiki.service';
import { WikiCardComponent } from './wiki-card.component';

/**
 * WikiListComponent displays a list of Wikipedia articles as cards with a search field.
 */
@Component({
  selector: 'app-wiki-list',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, WikiCardComponent],
  templateUrl: './wiki-list.component.html',
  styleUrls: ['./wiki-list.component.css']
})
export class WikiListComponent {
  searchControl = new FormControl('');
  articles = signal<WikiArticleSummary[]>([]);
  loading = signal(false);
  error = signal<string | null>(null);

  constructor(private wikiService: WikiService) {}

  fetchArticles(): void {
    const term = this.searchControl.value?.trim();
    if (!term) {
      this.error.set('Please enter a search term.');
      this.articles.set([]);
      return;
    }
    this.loading.set(true);
    this.error.set(null);
    this.wikiService.fetchArticles(term).subscribe({
      next: (results) => {
        this.articles.set(results);
        this.loading.set(false);
      },
      error: (err) => {
        this.error.set('Failed to fetch articles.');
        this.articles.set([]);
        this.loading.set(false);
      }
    });
  }
}

// code generated by AI
