import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { WikiArticleSummary } from '../services/wiki.service';

/**
 * WikiCardComponent displays a single Wikipedia article as a card.
 * @see WikiArticleSummary
 */
@Component({
  selector: 'app-wiki-card',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './wiki-card.component.html',
  styleUrls: ['./wiki-card.component.css']
})
export class WikiCardComponent {
  /**
   * The Wikipedia article to display.
   */
  @Input() article!: WikiArticleSummary;
}

// code generated by AI
