import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SearchBarComponent } from '../../components/search/search-bar.component';
import { ResultsListComponent } from '../../components/results/results-list.component';
import { WikiService, WikiSearchResult } from '../../services/wiki.service';
import { MatProgressSpinnerModule } from '@angular/material/progress-spinner';
import { MatSnackBar, MatSnackBarModule } from '@angular/material/snack-bar';
import { Subject, Observable, of } from 'rxjs';
import { catchError, finalize, switchMap, tap } from 'rxjs/operators';

/**
 * Home page displaying search bar and results.
 */
@Component({
  selector: 'app-home',
  standalone: true,
  imports: [
    CommonModule,
    SearchBarComponent,
    ResultsListComponent,
    MatProgressSpinnerModule,
    MatSnackBarModule
  ],
  templateUrl: './home.page.html',
  styleUrls: ['./home.page.css']
})
export class HomePage {
  private searchTerm$ = new Subject<string>();
  results$!: Observable<WikiSearchResult[]>;
  loading = false;
  error = '';

  constructor(private wikiService: WikiService, private snackBar: MatSnackBar) {
    this.results$ = this.searchTerm$.pipe(
      tap(() => {
        this.loading = true;
        this.error = '';
      }),
      switchMap(term =>
        this.wikiService.search(term).pipe(
          catchError(err => {
            this.error = err;
            this.snackBar.open(err, 'Close', { duration: 3000 });
            return of([] as WikiSearchResult[]);
          }),
          finalize(() => (this.loading = false))
        )
      )
    );
  }

  /**
   * Pushes the search term into the pipeline.
   * @param term The search term.
   */
  onSearch(term: string): void {
    this.searchTerm$.next(term);
  }
}

// code generated by AI
