import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { map, catchError } from 'rxjs/operators';
import { WikipediaApiResponse, WikipediaSearchResult } from '../models/wikipedia.model';

/**
 * Service for interacting with Wikipedia API
 */
@Injectable({
  providedIn: 'root'
})
export class WikipediaService {
  private readonly baseUrl = 'https://en.wikipedia.org/w/api.php';

  constructor(private http: HttpClient) {}

  /**
   * Search for Wikipedia articles based on search term
   * @param searchTerm The term to search for
   * @param limit Maximum number of results to return (default: 10)
   * @returns Observable of search results
   */
  searchArticles(searchTerm: string, limit: number = 10): Observable<WikipediaSearchResult[]> {
    if (!searchTerm.trim()) {
      return throwError(() => new Error('Search term cannot be empty'));
    }

    const params = new HttpParams()
      .set('action', 'query')
      .set('format', 'json')
      .set('list', 'search')
      .set('srsearch', searchTerm.trim())
      .set('srlimit', limit.toString())
      .set('origin', '*'); // CORS handling for Wikipedia API

    return this.http.get<WikipediaApiResponse>(this.baseUrl, { params }).pipe(
      map(response => this.transformApiResponse(response)),
      catchError(error => {
        console.error('Wikipedia API error:', error);
        return throwError(() => new Error('Failed to fetch search results. Please try again.'));
      })
    );
  }

  /**
   * Transform Wikipedia API response to application format
   * @param response Raw API response
   * @returns Transformed search results
   */
  private transformApiResponse(response: WikipediaApiResponse): WikipediaSearchResult[] {
    if (!response.query?.search) {
      return [];
    }

    return response.query.search.map(item => ({
      title: item.title,
      description: this.stripHtmlTags(item.snippet),
      url: `https://en.wikipedia.org/wiki/${encodeURIComponent(item.title.replace(/ /g, '_'))}`
    }));
  }

  /**
   * Remove HTML tags from Wikipedia snippet text
   * @param html HTML string to clean
   * @returns Clean text string
   */
  private stripHtmlTags(html: string): string {
    const doc = new DOMParser().parseFromString(html, 'text/html');
    return doc.body.textContent || '';
  }
}

// code generated by AI
