import { TestBed } from '@angular/core/testing';
import { HttpClientModule } from '@angular/common/http';
import { WikiService } from './wiki.service';

// Integration test using the real Wikipedia API

describe('WikiService (integration with real Wikipedia API)', () => {
  let service: WikiService;

  beforeEach(() => {
    TestBed.configureTestingModule({
      imports: [HttpClientModule],
      providers: [WikiService],
    });
    service = TestBed.inject(WikiService);
  });

  it('should fetch articles for a common search term', (done) => {
    service.fetchArticles('Angular').subscribe({
      next: (articles) => {
        expect(Array.isArray(articles)).toBeTrue();
        expect(articles.length).toBeGreaterThan(0);
        expect(articles[0].title).toBeTruthy();
        done();
      },
      error: (err) => {
        fail('API call failed: ' + err);
        done();
      }
    });
  });

  it('should return an empty array for gibberish search term', (done) => {
    service.fetchArticles('asdkjhasdkjhasd').subscribe({
      next: (articles) => {
        expect(Array.isArray(articles)).toBeTrue();
        expect(articles.length).toBe(0);
        done();
      },
      error: (err) => {
        fail('API call failed: ' + err);
        done();
      }
    });
  });
});

// code generated by AI
