import { Injectable } from '@angular/core';
import { HttpClient, HttpErrorResponse, HttpParams } from '@angular/common/http';
import { Observable, throwError } from 'rxjs';
import { catchError, map } from 'rxjs/operators';

/**
 * Shape of a Wikipedia search result
 */
export interface WikiSearchResult {
  title: string;
  snippet: string;
  pageid: number;
}

@Injectable({ providedIn: 'root' })
export class WikiService {
  private apiUrl = 'https://en.wikipedia.org/w/api.php';

  constructor(private http: HttpClient) {}

  /**
   * Searches Wikipedia for the given term and returns an array of results.
   */
  search(term: string): Observable<WikiSearchResult[]> {
    const params = new HttpParams()
      .set('action', 'query')
      .set('format', 'json')
      .set('list', 'search')
      .set('utf8', '1')
      .set('origin', '*')
      .set('srsearch', term);

    return this.http.get<any>(this.apiUrl, { params }).pipe(
      map((res) => res.query.search as WikiSearchResult[]),
      catchError(this.handleError)
    );
  }

  private handleError(err: HttpErrorResponse) {
    let errorMsg = 'An unknown error occurred.';
    if (err.error instanceof ErrorEvent) {
      errorMsg = `Error: ${err.error.message}`;
    } else {
      errorMsg = `Error ${err.status}: ${err.message}`;
    }
    return throwError(() => errorMsg);
  }
}

// code generated by AI
