import { Injectable } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable, map, catchError, throwError } from 'rxjs';

/**
 * Interface for Wikipedia search result item
 */
export interface WikipediaSearchResult {
  title: string;
  snippet: string;
  pageid: number;
  size: number;
  wordcount: number;
  timestamp: string;
}

/**
 * Interface for Wikipedia API response
 */
export interface WikipediaApiResponse {
  query: {
    search: WikipediaSearchResult[];
  };
}

/**
 * Service to interact with Wikipedia API
 */
@Injectable({
  providedIn: 'root',
})
export class WikiService {
  private readonly baseUrl = 'https://en.wikipedia.org/api/rest_v1';
  private readonly apiUrl = 'https://en.wikipedia.org/w/api.php';

  constructor(private http: HttpClient) {}

  /**
   * Search Wikipedia articles by search term
   * Uses the latest Wikipedia API (opensearch and query endpoints)
   * @param searchTerm - The term to search for
   * @param limit - Maximum number of results to return (default: 10)
   * @returns Observable with array of search results
   */
  searchArticles(
    searchTerm: string,
    limit: number = 10
  ): Observable<WikipediaSearchResult[]> {
    if (!searchTerm || searchTerm.trim().length === 0) {
      return throwError(() => new Error('Search term cannot be empty'));
    }

    const params = new HttpParams()
      .set('action', 'query')
      .set('list', 'search')
      .set('srsearch', searchTerm.trim())
      .set('format', 'json')
      .set('origin', '*')
      .set('srlimit', limit.toString())
      .set('srprop', 'snippet|titlesnippet|size|wordcount|timestamp');

    return this.http.get<WikipediaApiResponse>(this.apiUrl, { params }).pipe(
      map((response) => response.query.search),
      catchError((error) => {
        console.error('Error fetching Wikipedia articles:', error);
        return throwError(
          () => new Error('Failed to fetch Wikipedia articles')
        );
      })
    );
  }

  /**
   * Get a Wikipedia article summary by title
   * Uses the REST API v1 for better performance and structured data
   * @param title - The article title
   * @returns Observable with article summary
   */
  getArticleSummary(title: string): Observable<any> {
    if (!title || title.trim().length === 0) {
      return throwError(() => new Error('Article title cannot be empty'));
    }

    const encodedTitle = encodeURIComponent(title.trim());
    const url = `${this.baseUrl}/page/summary/${encodedTitle}`;

    return this.http.get(url).pipe(
      catchError((error) => {
        console.error('Error fetching article summary:', error);
        return throwError(() => new Error('Failed to fetch article summary'));
      })
    );
  }

  /**
   * Get random Wikipedia articles
   * @param count - Number of random articles to fetch (default: 1)
   * @returns Observable with array of random article titles
   */
  getRandomArticles(count: number = 1): Observable<string[]> {
    const params = new HttpParams()
      .set('action', 'query')
      .set('list', 'random')
      .set('format', 'json')
      .set('origin', '*')
      .set('rnlimit', Math.min(count, 10).toString())
      .set('rnnamespace', '0'); // Main namespace only

    return this.http.get<any>(this.apiUrl, { params }).pipe(
      map((response) => response.query.random.map((item: any) => item.title)),
      catchError((error) => {
        console.error('Error fetching random articles:', error);
        return throwError(() => new Error('Failed to fetch random articles'));
      })
    );
  }
}

// code generated by AI
