// WikiService: Fetches Wikipedia articles using the latest Wikipedia REST API
import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, map } from 'rxjs';

/**
 * Service for fetching Wikipedia articles using the latest Wikipedia API.
 */
@Injectable({
  providedIn: 'root',
})
export class WikiService {
  private readonly http = inject(HttpClient);
  private readonly apiUrl = 'https://en.wikipedia.org/w/rest.php/v1/search/title';

  /**
   * Fetches Wikipedia articles matching the given search term.
   * @param searchTerm The term to search for.
   * @param limit The maximum number of results to return (default: 10).
   * @returns An Observable emitting an array of article summaries.
   */
  fetchArticles(searchTerm: string, limit: number = 10): Observable<WikiArticleSummary[]> {
    const params = {
      q: searchTerm,
      limit: limit.toString(),
    };
    return this.http.get<WikiSearchResponse>(this.apiUrl, { params }).pipe(
      map(response => response.pages)
    );
  }
}

/**
 * Wikipedia search API response interface.
 */
export interface WikiSearchResponse {
  pages: WikiArticleSummary[];
}

/**
 * Wikipedia article summary interface.
 */
export interface WikiArticleSummary {
  id: number;
  key: string;
  title: string;
  excerpt: string;
  matched_title: string;
  description?: string;
  thumbnail?: {
    mimetype: string;
    width: number;
    height: number;
    url: string;
  };
}

// code generated by AI
