import { Component, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ReactiveFormsModule, FormControl } from '@angular/forms';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatButtonModule } from '@angular/material/button';

/**
 * Search bar component emits the search term when the user submits the form.
 */
@Component({
  selector: 'app-search-bar',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, MatFormFieldModule, MatInputModule, MatButtonModule],
  templateUrl: './search-bar.component.html',
  styleUrls: ['./search-bar.component.css']
})
export class SearchBarComponent {
  readonly searchControl = new FormControl('');

  @Output() search = new EventEmitter<string>();

  /**
   * Emits the search term if valid.
   */
  onSearch(): void {
    const term = this.searchControl.value?.trim();
    if (term) {
      this.search.emit(term);
    }
  }
}

// code generated by AI
